server.port=8008
spring.profiles.active=local
#log
#logging.level.org.hibernate.stat=debug
#logging.level.org.springframework=debug
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=debug
logging.level.root=info

#redis
spring.redis.host=192.168.2.194
spring.redis.port=6379
spring.redis.password=yNws*!bxPRoZ6P
spring.redis.database=1
spring.data.redis.repositories.enabled=false


